name: Beanstalk Deployment

on:
    workflow_dispatch:

jobs:
  beanstalk-deployment:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        application_name: CalculatorApp
        environment_name: CalculatorApp-Environment
        version_label: 1
        region: us-east-1
        deployment_package: deploy.zip
