name: Discord

on:
  push:
    branches:
      - main
      - 'feauture/*'
  pull_request:
      branches:
      - main
      - 'feauture/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6-beta
        with:
          repository: PXL-2TIN-DevOps-Resources/calculator-app-finished

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0

      - name: Install dependencies
        run: npm install

      - name: Run the code
        run: npm run build --if-present

      - name: Test the code
        run: npm test

      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        with:
          name: JEST JUnit
          path: junit.xml
          reporter: jest-junit

      - name: Better Test Reports Action
        id: test-coverage
        uses: mridang/action-test-reporter@v1.3.0
        with:
          coverage-file: junit.xml

      #- name: Archive production artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: app-package
      #    path: |
      #      *
      #      /usr/local/lib/node
      #      /usr/local/lib/node_modules
      
      - name: Discord Webhook Action - Vraag 1
        if: failure() || success()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Build status: ${{ job.status }}"

      - name: Discord Webhook Action - Vraag 2
        if: (github.ref_name == 'main' || startsWith(github.ref_name, 'feature')) && (github.event_name == 'push' || github.event_name == 'pull_request') && (success() || failure())
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "${{ github.event_name }} | ${{ github.ref_name }} | ${{ job.status }}"

      - name: Create comment - Vraag 3
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Build status: ${{ job.status }}
            Test coverage: ${{ steps.test-coverage.outputs.result }}

      - name: Discord Webhook Action - Vraag 4
        if: github.ref_name == 'main' && github.event_name == 'pull_request' && github.event.pull_request.state == 'open'
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "A pull request was opened for the main branch."
