name: Test Deployment

on:
    workflow_dispatch:

jobs:
  test-deployment:
    runs-on: self-hosted

    steps:
      - run: docker pull fred20/docker-complete:latest
      - run: docker ps -aq | xargs -r docker rm
      - run: docker run -d -p 3000:3000 fred20/docker-complete:latest
